services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true