services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn ecolive.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "ecolive.settings"
      - key: PYTHONUNBUFFERED
        value: "1"